{% set name = "mess-jax" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mess_jax-{{ version }}.tar.gz
  sha256: 72ed99c71f8e54045e08f1855303cb2663e71835a2138cae5532c9804ab48099

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - equinox
    - jax
    - jaxtyping
    - more-itertools
    - optax
    - optimistix
    - pandas
    - periodictable
    - pyarrow
    - pyscf
    - py3dmol
    - basis_set_exchange
    - sympy
    - importlib-resources

test:
  imports:
    - mess
  commands:
    - pip check
    - mess --help
  requires:
    - pip

about:
  home: https://github.com/valence-labs/mess
  summary: 'MESS: Modern Electronic Structure Simulations'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FNTwin
    - hatemhelal
